### PR TITLE
fix(core): Fix event forwarding to localhost (#195)

### LINKED ISSUE #195: Autoremediation is not working
Hi Keptn team,

I'm following the tutorial 'Keptn Full Tour on Prometheus' at the following link: https://tutorials.keptn.sh/tutorials/keptn-full-tour-prometheus-09.

I arrived at step 22 but no remediation is taking place.

I am able to see that an alert was fired:

Schermata 2021-11-24 alle 14 50 53

Following the tutorial, this should happen: 

> After receiving the alert notification, the prometheus-service will translate it into a Keptn CloudEvent. This event will eventually be received by the remediation-service that will look for a remediation action specified for this type of problem and, if found, execute it.

But nothing is really happening:

> kubectl get deployments -n sockshop-production
> NAME            READY   UP-TO-DATE   AVAILABLE   AGE
> carts           0/0     0            0           150m
> carts-db        1/1     1            1           4h49m
> carts-primary   1/1     1            1           149m

These are the logs of remediation-service container:

> {"timestamp":"2021-11-24T13:11:43.519506531Z","logLevel":"INFO","message":"Retrieving Prometheus metrics"}
> {"timestamp":"2021-11-24T13:11:43.521434128Z","logLevel":"INFO","message":"Checking if external prometheus instance has been defined for project sockshop"}
> {"timestamp":"2021-11-24T13:11:43.531984705Z","logLevel":"INFO","message":"could not retrieve or read secret: secrets \"prometheus-credentials-sockshop\" not found"}
> {"timestamp":"2021-11-24T13:11:43.53201841Z","logLevel":"INFO","message":"No external prometheus instance defined for project sockshop. Using default: http://prometheus-server.monitoring.svc.cluster.local:80"}
> {"timestamp":"2021-11-24T13:11:43.532078402Z","logLevel":"INFO","message":"Checking for custom SLI queries"}
> {"timestamp":"2021-11-24T13:14:27.704992632Z","logLevel":"INFO","message":"Retrieving Prometheus metrics"}
> {"timestamp":"2021-11-24T13:14:27.706381476Z","logLevel":"INFO","message":"Checking if external prometheus instance has been defined for project sockshop"}
> {"timestamp":"2021-11-24T13:14:27.714339435Z","logLevel":"INFO","message":"could not retrieve or read secret: secrets \"prometheus-credentials-sockshop\" not found"}
> {"timestamp":"2021-11-24T13:14:27.714365153Z","logLevel":"INFO","message":"No external prometheus instance defined for project sockshop. Using default: http://prometheus-server.monitoring.svc.cluster.local:80"}
> {"timestamp":"2021-11-24T13:14:27.71439437Z","logLevel":"INFO","message":"Checking for custom SLI queries"}
> {"timestamp":"2021-11-24T13:14:28.184957853Z","logLevel":"INFO","message":"Fetching indicator: response_time_p95"}
> {"timestamp":"2021-11-24T13:14:28.185077409Z","logLevel":"INFO","message":"Generated query: /api/v1/query?query=histogram_quantile(0.95,sum(rate(http_response_time_milliseconds_bucket{job='carts-sockshop-staging-canary'}[76s]))by(le))\u0026time=1637759667"}
> {"timestamp":"2021-11-24T13:14:28.199903134Z","logLevel":"INFO","message":"Prometheus Result is 0, returning value 0"}
> {"timestamp":"2021-11-24T13:30:07.978235232Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.monitoring.configure"}
> {"timestamp":"2021-11-24T13:30:07.97866627Z","logLevel":"DEBUG","message":"Check if prometheus service in monitoring namespace is available"}
> {"timestamp":"2021-11-24T13:30:08.003521137Z","logLevel":"DEBUG","message":"Prometheus service in monitoring namespace is available"}
> {"timestamp":"2021-11-24T13:30:08.003550012Z","logLevel":"DEBUG","message":"Configure prometheus monitoring with keptn"}
> {"timestamp":"2021-11-24T13:30:08.39239494Z","logLevel":"INFO","message":"No SLO file found for stage dev. No alerting rules created for this stage"}
> {"timestamp":"2021-11-24T13:30:09.091748977Z","logLevel":"INFO","message":"Using default query for response_time_p95"}
> {"timestamp":"2021-11-24T13:30:09.813053626Z","logLevel":"DEBUG","message":"Configure prometheus alert manager with keptn"}
> {"timestamp":"2021-11-24T13:30:09.813084835Z","logLevel":"INFO","message":"Configuring Prometheus AlertManager..."}
> {"timestamp":"2021-11-24T13:30:09.814288854Z","logLevel":"INFO","message":"Creating Prometheus AlertManager Template configmap..."}
> {"timestamp":"2021-11-24T13:30:09.822227909Z","logLevel":"ERROR","message":"configmaps \"alertmanager-templates\" already exists"}
> {"timestamp":"2021-11-24T13:30:10.227325617Z","logLevel":"DEBUG","message":"Received event: sh.keptn.event.monitoring.configure"}
> {"timestamp":"2021-11-24T13:30:10.227406746Z","logLevel":"DEBUG","message":"Check if prometheus service in monitoring namespace is available"}
> {"timestamp":"2021-11-24T13:30:10.234680723Z","logLevel":"DEBUG","message":"Prometheus service in monitoring namespace is available"}
> {"timestamp":"2021-11-24T13:30:10.234710563Z","logLevel":"DEBUG","message":"Configure prometheus monitoring with keptn"}
> {"timestamp":"2021-11-24T13:30:10.590733913Z","logLevel":"INFO","message":"No SLO file found for stage dev. No alerting rules created for this stage"}
> {"timestamp":"2021-11-24T13:30:11.391234193Z","logLevel":"INFO","message":"Using default query for response_time_p95"}
> {"timestamp":"2021-11-24T13:30:12.202778881Z","logLevel":"DEBUG","message":"Configure prometheus alert manager with keptn"}
> {"timestamp":"2021-11-24T13:30:12.202812925Z","logLevel":"INFO","message":"Configuring Prometheus AlertManager..."}
> {"timestamp":"2021-11-24T13:30:12.203776171Z","logLevel":"INFO","message":"Creating Prometheus AlertManager Template configmap..."}
> {"timestamp":"2021-11-24T13:30:12.212248226Z","logLevel":"ERROR","message":"configmaps \"alertmanager-templates\" already exists"}

These are the logs of remediation-service distributor container:

> time="2021-11-24T13:11:43Z" level=info msg="Received a message for topic [sh.keptn.event.get-sli.triggered]\n"
> time="2021-11-24T13:11:43Z" level=info msg="Received CloudEvent with ID 099fd70d-3d01-4f4e-a295-5189d6b2c674 - Forwarding to Keptn API\n"
> time="2021-11-24T13:11:43Z" level=error msg="No external API endpoint defined. Forwarding directly to NATS server"
> time="2021-11-24T13:11:43Z" level=info msg="Sent: 099fd70d-3d01-4f4e-a295-5189d6b2c674, accepted: true"
> time="2021-11-24T13:11:43Z" level=info msg="UniformLogger: received event: sh.keptn.event.get-sli.started"
> time="2021-11-24T13:11:44Z" level=info msg="Received CloudEvent with ID 9c6136cf-ec0a-413f-8341-efb3b9363da3 - Forwarding to Keptn API\n"
> time="2021-11-24T13:11:44Z" level=error msg="No external API endpoint defined. Forwarding directly to NATS server"
> time="2021-11-24T13:11:44Z" level=info msg="Sent: 9c6136cf-ec0a-413f-8341-efb3b9363da3, accepted: true"
> time="2021-11-24T13:11:44Z" level=info msg="UniformLogger: received event: sh.keptn.event.get-sli.finished"
> time="2021-11-24T13:11:44Z" level=info msg="sent event 43a9a9b2-815d-4b32-9b8c-cfc0508c90df"
> time="2021-11-24T13:14:27Z" level=info msg="Received a message for topic [sh.keptn.event.get-sli.triggered]\n"
> time="2021-11-24T13:14:27Z" level=info msg="Received CloudEvent with ID 1ed9f356-147f-4fe2-a715-9c9337cb48dc - Forwarding to Keptn API\n"
> time="2021-11-24T13:14:27Z" level=error msg="No external API endpoint defined. Forwarding directly to NATS server"
> time="2021-11-24T13:14:27Z" level=info msg="UniformLogger: received event: sh.keptn.event.get-sli.started"
> time="2021-11-24T13:14:27Z" level=info msg="Sent: 1ed9f356-147f-4fe2-a715-9c9337cb48dc, accepted: true"
> time="2021-11-24T13:14:28Z" level=info msg="Received CloudEvent with ID d335f0a8-2424-42ea-9606-f80fafd0cecd - Forwarding to Keptn API\n"
> time="2021-11-24T13:14:28Z" level=error msg="No external API endpoint defined. Forwarding directly to NATS server"
> time="2021-11-24T13:14:28Z" level=info msg="UniformLogger: received event: sh.keptn.event.get-sli.finished"
> time="2021-11-24T13:14:28Z" level=info msg="Sent: d335f0a8-2424-42ea-9606-f80fafd0cecd, accepted: true"
> time="2021-11-24T13:14:28Z" level=info msg="sent event aa8a8260-06e1-42a4-9094-a8acae528311"
> time="2021-11-24T13:30:07Z" level=info msg="Received a message for topic [sh.keptn.event.monitoring.configure]\n"
> time="2021-11-24T13:30:09Z" level=info msg="Received CloudEvent with ID 7469d375-99ca-448a-8932-dc25a89b7427 - Forwarding to Keptn API\n"
> time="2021-11-24T13:30:09Z" level=error msg="No external API endpoint defined. Forwarding directly to NATS server"
> time="2021-11-24T13:30:09Z" level=info msg="Sent: 7469d375-99ca-448a-8932-dc25a89b7427, accepted: true"
> time="2021-11-24T13:30:09Z" level=info msg="UniformLogger: received event: sh.keptn.event.configure-monitoring.finished"
> time="2021-11-24T13:30:09Z" level=info msg="UniformLogger: received .finished event with status errored. forwarding log message to log ingestion API"
> time="2021-11-24T13:30:12Z" level=info msg="Received CloudEvent with ID 1aa0256d-84ac-4f63-9003-2d94da9d924b - Forwarding to Keptn API\n"
> time="2021-11-24T13:30:12Z" level=error msg="No external API endpoint defined. Forwarding directly to NATS server"
> time="2021-11-24T13:30:12Z" level=info msg="Sent: 1aa0256d-84ac-4f63-9003-2d94da9d924b, accepted: true"
> time="2021-11-24T13:30:12Z" level=info msg="UniformLogger: received event: sh.keptn.event.configure-monitoring.finished"
> time="2021-11-24T13:30:12Z" level=info msg="UniformLogger: received .finished event with status errored. forwarding log message to log ingestion API"
> time="2021-11-24T13:30:13Z" level=info msg="sent event 2b54505b-fb2d-473f-8372-1be8d62cd321"

There are no logs of remediation-service container.

These are the logs of remediation-service distributor container:

> kubectl logs remediation-service-7d57db9d6-sb5nm -n keptn -c distributor
> time="2021-11-24T08:29:26Z" level=info msg="Starting Event Forwarder"
> time="2021-11-24T08:29:26Z" level=info msg="Registering Keptn Intgration"
> time="2021-11-24T08:29:27Z" level=warning msg="Unable to register to Keptn's control plane: Post \"http://shipyard-controller:8080/v1/uniform/registration\": dial tcp 10.104.7.131:8080: connect: connection refused"
> time="2021-11-24T08:29:33Z" level=warning msg="Unable to register to Keptn's control plane: Post \"http://shipyard-controller:8080/v1/uniform/registration\": dial tcp 10.104.7.131:8080: connect: connection refused"
> time="2021-11-24T08:29:39Z" level=warning msg="Unable to register to Keptn's control plane: Post \"http://shipyard-controller:8080/v1/uniform/registration\": dial tcp 10.104.7.131:8080: connect: connection refused"
> time="2021-11-24T08:29:45Z" level=warning msg="Unable to register to Keptn's control plane: Post \"http://shipyard-controller:8080/v1/uniform/registration\": dial tcp 10.104.7.131:8080: connect: connection refused"
> time="2021-11-24T08:29:51Z" level=warning msg="Unable to register to Keptn's control plane: Post \"http://shipyard-controller:8080/v1/uniform/registration\": dial tcp 10.104.7.131:8080: connect: connection refused"
> time="2021-11-24T08:29:57Z" level=warning msg="Unable to register to Keptn's control plane: Post \"http://shipyard-controller:8080/v1/uniform/registration\": dial tcp 10.104.7.131:8080: connect: connection refused"
> time="2021-11-24T08:30:03Z" level=warning msg="Unable to register to Keptn's control plane: Post \"http://shipyard-controller:8080/v1/uniform/registration\": dial tcp 10.104.7.131:8080: connect: connection refused"
> time="2021-11-24T08:30:09Z" level=warning msg="Unable to register to Keptn's control plane: Post \"http://shipyard-controller:8080/v1/uniform/registration\": dial tcp 10.104.7.131:8080: connect: connection refused"
> time="2021-11-24T08:30:15Z" level=info msg="Registered Keptn Integration with id ebaf72c04509556c5fb07961688c45f3e9a6aec7"
> time="2021-11-24T08:30:15Z" level=info msg="Starting UniformLog for Keptn service with integration ID ebaf72c04509556c5fb07961688c45f3e9a6aec7"
> time="2021-11-24T08:30:15Z" level=info msg="Connection type: nats"
> time="2021-11-24T08:30:15Z" level=info msg="Starting NATS event Receiver"
> time="2021-11-24T08:30:15Z" level=info msg="Connecting to NATS server at nats://keptn-nats-cluster ..."
> time="2021-11-24T08:30:15Z" level=info msg="Connected to NATS server"
> time="2021-11-24T08:30:15Z" level=info msg="Subscribing to topic sh.keptn.event.get-action.triggered ..."
> time="2021-11-24T08:30:15Z" level=info msg="Subscribed to topic sh.keptn.event.get-action.triggered"

I'm using KEPTN_VERSION=0.9.0, ISTIO_VERSION=1.11.2, Prometheus service manifest at version 0.7.0.

From what I can understand, remediation is not listening to any event or no event is written to the topic sh.keptn.event.get-action.triggered

### PR DESCRIPTION
**Pull request by christian-kreuzberger-dtx**
## This PR

- Fixes the event forwarding when a cloudevent is received on port 8080 via the golang http handler
- Updates dockerignore to speed up docker build 

Fixes #195

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -54,23 +55,31 @@ type ceTest struct {
...
 	namespace          = os.Getenv("POD_NAMESPACE")
 	prometheusEndpoint = os.Getenv("PROMETHEUS_ENDPOINT")
+	env                envConfig
 )
 
 func main() {
-	// listen on port 8080 for any event
+	/**
+	Note that we open two ports, 8080 and env.Port (e.g., 8082).
+	Everything goes in via 8080, but if it's a cloudevent, we forward it internally to 8082
```
Comment (solidnerd) [inline main.go:64]: What is the reason behind to have thee different ports right now ? 

Also what is the Job of Port `8080`
* Proxy Cloud Events 
* Being Reachable for the Alertmanager WebHook Call

The `8080` seems to be the ingress (proxy for cloud right now and `8082` is the cloud events and prometheus webhook call)

Comment (solidnerd) [reply main.go:64]: I think it would be a nice improvement to mention the responsibilities of the Ports also in the README.
Then it is more clear to external users what the port is capable of.

Comment (christian-kreuzberger-dtx) [reply main.go:64]: Port 8081 is taken by the Keptn distributor within the sidecar.
Port 8080 is the primary port that this pod is listening too (and the only one a user needs to know about)
Port 8082 is for internal usage, it takes cloudevents using the cloudevents sdk.

I'd like to get rid of 8082, but that's a different story and requires refactoring way beyond the scope of this bugfix.

I'll update the information in README though.

Comment (christian-kreuzberger-dtx) [reply main.go]: Updated PR

**Review by bacherfl — APPROVED** [review]

**Comment by braghettos** [comment]
@christian-kreuzberger-dtx do you think this fix will be release in 0.7.2 version or it will be backported?

**Comment by christian-kreuzberger-dtx** [comment]
We will release version 0.7.2 which will contain this fix.
In the meantime you could use the following docker image to verify that everything is working:
```
keptncontrib/prometheus-service:0.7.2-dev.202112020803
```

Please note that this is an unofficial nightly image.
